<a href="https://colab.research.google.com/github/julienessan/Gomycode_Cours_Data_Sciences/blob/main/Checkpoint_Entra%C3%AEner_mod%C3%A8le_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Checkpoint: Entraîner et évaluer un modèle (jeu de données Iris)

**Objectif**

Démontrer votre capacité à former un modèle d'apprentissage automatique supervisé et à évaluer ses performances à l'aide de l'ensemble de données classique Iris.

In [ ]:
#Importer le jeu de données
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the Iris dataset
iris_data = load_iris()

# Create a DataFrame from the data and feature names
iris = pd.DataFrame(data=iris_data.data, columns=iris_data.feature_names)

In [5]:
#Explorer les données
iris.shape

(150, 5)

In [9]:
X = iris_data.data
y = iris_data.target
feature_names = iris_data.feature_names
target_names = iris_data.target_names
print("Feature names:", feature_names)
print("Target names:", target_names)
print("\nFirst 10 rows of X:\n", X[:10])

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']

First 10 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [10]:
# Diviser les données
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
 X, y, test_size = 0.2, random_state = 42
)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)


(120, 4)
(30, 4)
(120,)
(30,)


In [11]:
# Entraîner un classificateur arbre de décision
from sklearn.tree import DecisionTreeClassifier, plot_tree
#Initialiser le modèle
mod_dt = DecisionTreeClassifier(max_depth = 3, random_state = 1)
#entaîner le modèle
mod_dt.fit(X_train,y_train)
#Utilisé le modèle entrainé avec training set pour prédire test set
prediction=mod_dt.predict(X_test)
print(prediction)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [12]:
#Imprimer le score de précision
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,prediction))

1.0


In [13]:
# Afficher la matrice de confusion (optionnel : visualisation avec seaborn.heatmap)
from sklearn.metrics import confusion_matrix
mat_conf = confusion_matrix(y_test, prediction)
print(mat_conf)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


# Interprétation : Dans quelle mesure le modèle a-t-il permis de classer chaque espèce ?


En regardant la matrice de confusion, nous pouvons voir que :

- **10 instances de 'setosa' (espèce 0) ont été correctement classées.**
- **9 instances de 'versicolor' (espèce 1) ont été correctement classées.**
- **11 instances de 'virginica' (espèce 2) ont été correctement classées.**

Toutes les prédictions ont été correctes pour chaque espèce, ce qui indique que le modèle a parfaitement classé tous les échantillons du jeu de test. Ceci est cohérent avec le score de précision de 1,0 précédemment calculé.