<a href="https://colab.research.google.com/github/julienessan/Gomycode_Cours_Data_Sciences/blob/main/Checkpoint_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Checkpoint: NUMPY**

**Objectif**

Dans cet exercice, vous allez créer un programme qui calcule les notes des étudiants en utilisant des tableaux NumPy. Le programme demandera à l'utilisateur de saisir le nombre d'étudiants, le nombre de matières et les notes de chaque étudiant dans chaque matière. Il calculera ensuite les notes totales, le pourcentage et la mention pour chaque étudiant en utilisant des tableaux NumPy. Le programme affichera les résultats pour chaque étudiant dans un format tabulaire.

In [1]:
import numpy as np

In [15]:
Nb_etudiant = int(input("Saisir le nombre d'étudiants : "))
Nb_matiere = int(input("Saisir le nombre de matières : "))

Saisir le nombre d'étudiants : 4
Saisir le nombre de matières : 2


In [17]:
# Créez un tableau NumPy pour stocker les notes de chaque étudiant dans chaque matière. Le tableau doit avoir la forme (nombre d'étudiants, nombre de matières).
note_etudiant = np.zeros((Nb_etudiant, Nb_matiere))
print(note_etudiant)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [18]:
# Demandez à l'utilisateur de saisir les notes de chaque étudiant dans chaque matière.
for i in range(Nb_etudiant):
    for j in range(Nb_matiere):
        note_etudiant[i, j] = float(input(f"Saisir la note de l'étudiant {i+1} dans la matière {j+1}: "))


Saisir la note de l'étudiant 1 dans la matière 1: 15
Saisir la note de l'étudiant 1 dans la matière 2: 15
Saisir la note de l'étudiant 2 dans la matière 1: 13
Saisir la note de l'étudiant 2 dans la matière 2: 9
Saisir la note de l'étudiant 3 dans la matière 1: 17
Saisir la note de l'étudiant 3 dans la matière 2: 15
Saisir la note de l'étudiant 4 dans la matière 1: 9
Saisir la note de l'étudiant 4 dans la matière 2: 10


In [19]:
print(note_etudiant)

[[15. 15.]
 [13.  9.]
 [17. 15.]
 [ 9. 10.]]


In [30]:
#Calculez les notes totales pour chaque étudiant en utilisant la fonction sum() de NumPy.
total_note = np.sum(note_etudiant, axis=1)
print(total_note)

[30. 22. 32. 19.]


In [35]:
#Calculez le pourcentage pour chaque étudiant en utilisant les notes totales et la formule : pourcentage = (notes totales / (nombre de matières * 100)) * 100
pourcentage = ((total_note / (Nb_matiere * 100)) * 100)
print(type(pourcentage))

<class 'numpy.ndarray'>


In [28]:
#Calculez la mention pour chaque étudiant en utilisant le pourcentage et le système de notation suivant :
#90 % ou plus : A+
#80 % ou plus : A
#70 % ou plus : B+
#60 % ou plus : B
#50 % ou plus : C
#En dessous de 50 % : F
mention = np.where(pourcentage >= 90, 'A+',
               np.where(pourcentage >= 80, 'A',
               np.where(pourcentage >= 70, 'B+',
               np.where(pourcentage >= 60, 'B',
               np.where(pourcentage >= 50, 'C',
               'F')))))



In [29]:
#Affichez les résultats pour chaque étudiant dans un format tabulaire avec des colonnes pour le nom de l'étudiant, les notes totales, le pourcentage et la mention.
print("Nom de l'étudiant\tNotes totales\tPourcentage\tMention")
for i in range(Nb_etudiant):
    print(f"Étudiant {i+1}\t\t{total_note[i]}\t\t{pourcentage[i]}\t\t{mention[i]}")

Nom de l'étudiant	Notes totales	Pourcentage	Mention
Étudiant 1		30.0		15.0		F
Étudiant 2		22.0		11.0		F
Étudiant 3		32.0		16.0		F
Étudiant 4		19.0		9.5		F
